import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Sparkles } from 'lucide-react';
import { getMetrics, getTickets, getWeeklyDigest } from '../api/client';
import DashboardMetrics from '../components/DashboardMetrics';
import AskTicketsChat from '../components/AskTicketsChat';
import { formatDistanceToNow } from 'date-fns';

export default function Dashboard() {
  const navigate = useNavigate();

  const { data: metrics, isLoading: loadingMetrics } = useQuery({
    queryKey: ['metrics'],
    queryFn: getMetrics,
  });

  const { data: recentTickets, isLoading: loadingTickets } = useQuery({
    queryKey: ['tickets', { status: 'open', size: 5 }],
    queryFn: () => getTickets({ status: 'open', size: 5, page: 1 }),
  });

  const { data: digest, isLoading: loadingDigest } = useQuery({
    queryKey: ['weekly-digest'],
    queryFn: getWeeklyDigest,
  });

  return (
    <div className="flex flex-col gap-5">
      {loadingMetrics ? (
        <div className="animate-pulse h-24 bg-gray-200 rounded-lg"></div>
      ) : (
        <DashboardMetrics metrics={metrics} />
      )}

      <div className="two-col">
        <div className="card">
          <div className="card-title">Recent open tickets</div>
          {loadingTickets ? (
             <div className="animate-pulse h-40 bg-gray-100 rounded-md"></div>
          ) : recentTickets?.items?.length > 0 ? (
            <div className="flex flex-col">
              {recentTickets.items.map(ticket => (
                <div 
                  key={ticket.id} 
                  className="ticket-row" 
                  onClick={() => navigate(`/tickets/${ticket.id}`)}
                >
                  <span className="tid">#{ticket.id}</span>
                  <span className="ttitle">{ticket.title}</span>
                  <span className={`badge ${ticket.priority}`}>{ticket.priority}</span>
                  <span className="ttime">
                    {formatDistanceToNow(new Date(ticket.created_at), { addSuffix: true })}
                  </span>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-sm text-gray-500">No recent open tickets.</div>
          )}
        </div>

        <div className="card">
          <div className="card-title">AI weekly digest</div>
          <div className="digest-box">
            <div className="digest-ai-tag"><Sparkles size={12} /> Generated by Claude AI</div>
            <div className="digest-text">
              {loadingDigest ? 'Generating digest...' : digest?.digest || 'Digest unavailable.'}
            </div>
          </div>
        </div>
      </div>

      <div className="two-col">
        <div className="card">
          <div className="card-title">Tickets by category — this week</div>
          <div className="cat-grid">
            {metrics?.tickets_by_category && Object.entries(metrics.tickets_by_category).map(([cat, count]) => (
              <div key={cat} className="cat-card">
                <div className="cat-label capitalize">{cat.replace('_', ' ')}</div>
                <div className="cat-val">{count}</div>
              </div>
            ))}
          </div>
        </div>

        <AskTicketsChat />
      </div>
    </div>
  );
}
